# Generated by Django 4.1 on 2022-08-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, default='house-icon-png-17.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_profile_picture',
            field=models.ImageField(blank=True, default='Employee__business_man.png', null=True, upload_to='images'),
        ),
    ]
