# Generated by Django 4.1 on 2022-08-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Projects', '0003_alter_projects_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff_Projects.staff')),
            ],
        ),
    ]
