# Generated by Django 4.1 on 2022-08-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Projects', '0004_major_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
