# Generated by Django 4.1 on 2022-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Projects', '0005_alter_projects_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee_previous_project',
            field=models.ManyToManyField(blank=True, related_name='participants', to='Staff_Projects.projects'),
        ),
    ]
